name: Check file change action

on:
  workflow_call:

jobs:
  check_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print summary
        run: |
          echo "Called workflow run successful" >> $GITHUB_STEP_SUMMARY
